[package]
name = "ore-no-rdb"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
pest = "2.6"
pest_derive = "2.6"
rustyline = "17.0.1"
clap = { version = "4.0", features = ["derive"] }
glob = "0.3.2"
uuid = { version = "1.19.0", features = ["v4"] }
